spring:
  kafka:
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping : "Pet:com.dissi.kafkaworkshop.kafka.model.Pet"
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.LongDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: com.dissi.kafkaworkshop.kafka.model.Pet
        spring.deserializer.key.function: com.dissi.kafkaworkshop.kafka.handler.DeserializerKeyHandler
        spring.deserializer.value.function: com.dissi.kafkaworkshop.kafka.handler.DeserializerValueHandler
---
# TODO: Fill me with data from https://kafka.dissi.me/?tab=me !
